working-dir: /usr/local/server
params:
  - CONFIGURATION=PROD
env-vars:
  - SERVER_KIND=minecraft.vanilla
prelaunch-scripts:
  - test.sh
  - configure-env.sh
  - configure-server.sh
run-cmd:
  cmd: java
  args:
    - -server
    - -Xms1024M
    - -Xmx2000M
    - -jar
    - server.jar
    - nogui
