environment-variables:
  AWS_ACCESS_KEY_ID: v5wIxDEarnzQLz8M7W7e
  AWS_SECRET_ACCESS_KEY: j1CspYKmYCh8eUIkl8pCXAuBxZhhddfjLUXkw9kL

app:
  configuration: debug
  port: 8989
  services:
    server-messaging:
      rcon:
        enabled: true
        server-rcon-port: 25575
        server-rcon-password: kirieshki-rcon
    server-info:
      query:
        enabled: true
        server-query-port: 25565
    server-logging:
      enabled: true
      logging-system: file
      page-size: 300
      log-file: ./my-log
    server-files:
      s3:
        enabled: true
        endpoint: http://localhost:9000
      worker-pool:
        worker-count: 3
        queue-size: 100


  
server:
  startup-config: ./startup-config.yml