working-dir: /home/blackpoint/Projects/SimpleHosting/minecraft-server-playground/
params:
  - CONFIGURATION=PROD
env-vars:
  - SERVER_KIND=minecraft.vanilla
prelaunch-scripts:
  - test.sh
  - configure-env.sh
  - configure-server.sh
run-cmd:
  cmd: java
  args:
    - -jar
    - server.jar
    - nogui
