working-dir: .
params:
  - CONFIGURATION=PROD
env-vars:
  - SERVER_KIND=minecraft.vanilla
prelaunch-scripts:
  - test.sh
  - configure-env.sh
  - configure-server.sh
run-cmd:
  cmd: java
  args:
    - -jar
    - /home/blackpoint/Games/minecraft/TLauncher-2.876.jar
